// The two-engine harness's HOST. Committed under ios_overlay/ and copied over
// ios/Runner/AppDelegate.swift by selfhost/scripts/prepare_twoengine_fixture.sh.
//
// WHY IT CANNOT BE AN IN-PLACE EDIT. ios/ is generated by `flutter create` and
// gitignored, so an edited AppDelegate.swift is deleted by the next materialize.
// The prepare script's precedent is re-injection — airgap's script re-adds two
// Info.plist keys every time — so the Swift lives here and is copied in.
//
// WHAT THIS HOST PROVES, AND WHAT IT DELIBERATELY DOES NOT
//
//   proves (structurally): two FlutterEngines, each built from its OWN
//   FlutterDartProject, each running a DISTINCT Dart entrypoint, in one process.
//
//   does NOT prove: anything about Route B arming. This runs on stock Flutter
//   against a simulator, so it cannot observe arming even in principle, and a
//   green run here must never be reported against G15. Construction/boot success
//   and arming state are separate observations and are logged as such.
import Flutter
import UIKit

@main
@objc class AppDelegate: FlutterAppDelegate, FlutterImplicitEngineDelegate {
  private var engineOne: FlutterEngine?
  private var engineTwo: FlutterEngine?

  /// THE TRIPWIRE. The generated Runner boots an IMPLICIT engine via
  /// `UIMainStoryboardFile = Main`; construct two on top of that and the process
  /// holds THREE, which makes every per-engine reading unattributable.
  ///
  /// The prepare script deletes that plist key, so this delegate method must
  /// never fire. If it does, the harness REFUSES rather than interpreting: a
  /// third engine is not a finding about arming, it is a broken harness, and
  /// reporting anything from a three-engine process would be worse than
  /// reporting nothing.
  private var sawImplicitEngine = false

  /// The host's findings, accumulated and then written to a file.
  ///
  /// NOT NSLog. Measured 2026-08-13: NSLog from a simulator app reaches neither
  /// `flutter run`'s output nor `xcrun simctl spawn <udid> log show`, so host-side
  /// facts logged that way are simply unobservable — while the Dart side's
  /// `print` arrives fine. Since the whole point of this harness is that the host
  /// facts (no implicit engine, two distinct projects, two boots) are readable
  /// SEPARATELY from the Dart facts, they go to a file in the same tmp directory
  /// the Dart markers use.
  private var findings: [String] = []

  func didInitializeImplicitFlutterEngine(_ engineBridge: FlutterImplicitEngineBridge) {
    sawImplicitEngine = true
    record("REFUSE reason=implicit_engine_initialized")
  }

  /// Append a finding, and mirror it to NSLog for a human watching Console.
  private func record(_ line: String) {
    findings.append(line)
    NSLog("G15-HOST \(line)")
  }

  /// Write the host's findings beside the Dart markers.
  private func writeHostMarker() {
    let path = (NSTemporaryDirectory() as NSString)
      .appendingPathComponent("g15-host.marker")
    let body = findings.joined(separator: "\n") + "\n"
    do {
      try body.write(toFile: path, atomically: true, encoding: .utf8)
      NSLog("G15-HOST marker_path=\(path)")
    } catch {
      NSLog("G15-HOST marker_failed error=\(error)")
    }
  }

  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    // super FIRST, because the implicit engine (if any) is created inside it
    // during storyboard load — so the tripwire has fired by the time we check.
    let superResult = super.application(application, didFinishLaunchingWithOptions: launchOptions)

    record("implicit_engine=\(sawImplicitEngine ? 1 : 0)")
    if sawImplicitEngine {
      record("engines_constructed=0 refused=1")
      writeHostMarker()
      showRefusal("implicit engine still alive — delete UIMainStoryboardFile")
      return superResult
    }

    // TWO PROJECTS, ONE PER ENGINE, AND THIS IS THE LOAD-BEARING PART.
    //
    // FlutterDartProject's -init reaches ConfigureShorebird through
    // FLTDefaultSettingsForBundle, so one project per engine means TWO
    // ConfigureShorebird calls — and the second is exactly the case patch 0007
    // fixes (the updater's second shorebird_init deliberately fails, and arming
    // used to sit below a return gated on it).
    //
    // A SHARED project is the false-pass shape: FlutterEngine copies
    // [self.dartProject settings] into the Shell, so a shared project hands
    // engine two an already-armed root_isolate_create_callback and it runs
    // patched code even WITHOUT 0007. There is deliberately NO fallback that
    // retries with a shared project when engine two fails to boot: if only the
    // shared shape boots, that is not evidence for the G15 claim and the run
    // must fail rather than degrade into the shape that always looks green.
    //
    // For the same reason: never FlutterEngineGroup, never spawnWithEntrypoint —
    // both pass the parent's project.
    let projectOne = FlutterDartProject()
    let projectTwo = FlutterDartProject()
    let projectsDistinct = projectOne !== projectTwo
    record("projects_distinct=\(projectsDistinct ? 1 : 0) "
      + "p1=\(UInt(bitPattern: ObjectIdentifier(projectOne).hashValue)) "
      + "p2=\(UInt(bitPattern: ObjectIdentifier(projectTwo).hashValue))")

    let one = FlutterEngine(
      name: "g15-engine-one", project: projectOne, allowHeadlessExecution: true)
    let two = FlutterEngine(
      name: "g15-engine-two", project: projectTwo, allowHeadlessExecution: true)
    engineOne = one
    engineTwo = two

    // Engine one takes the default entrypoint (`main`); engine two takes
    // `engineTwoMain`, which carries vm:entry-point so it also survives AOT.
    let ranOne = one.run()
    let ranTwo = two.run(withEntrypoint: "engineTwoMain")

    record("engines_constructed=2 engine_one_run=\(ranOne ? 1 : 0) "
      + "engine_two_run=\(ranTwo ? 1 : 0) "
      + "engines_distinct=\(one !== two ? 1 : 0) "
      + "e1=\(UInt(bitPattern: ObjectIdentifier(one).hashValue)) "
      + "e2=\(UInt(bitPattern: ObjectIdentifier(two).hashValue))")

    // Arming is a SEPARATE observation and is not made here. Saying so in the log
    // is cheaper than a future reader inferring it from a green boot.
    record("arming_observed=0 reason=host_does_not_observe_arming")
    writeHostMarker()

    // Build the window ourselves — engine one gets the visible view, engine two
    // runs headless, which is the shape the G15 bug was reported in.
    let controller = FlutterViewController(engine: one, nibName: nil, bundle: nil)
    let w = UIWindow(frame: UIScreen.main.bounds)
    w.rootViewController = controller
    window = w
    w.makeKeyAndVisible()

    return superResult
  }

  /// A visible, unmistakable refusal. A crash would also refuse, but a red screen
  /// with the reason on it survives into a screenshot.
  private func showRefusal(_ reason: String) {
    let label = UILabel()
    label.text = "G15 HARNESS REFUSED\n\(reason)"
    label.numberOfLines = 0
    label.textAlignment = .center
    label.textColor = .white
    let vc = UIViewController()
    vc.view.backgroundColor = .systemRed
    vc.view.addSubview(label)
    label.translatesAutoresizingMaskIntoConstraints = false
    NSLayoutConstraint.activate([
      label.centerXAnchor.constraint(equalTo: vc.view.centerXAnchor),
      label.centerYAnchor.constraint(equalTo: vc.view.centerYAnchor),
      label.widthAnchor.constraint(equalTo: vc.view.widthAnchor, multiplier: 0.8),
    ])
    let w = UIWindow(frame: UIScreen.main.bounds)
    w.rootViewController = vc
    window = w
    w.makeKeyAndVisible()
  }
}
