#!/usr/bin/env bash
#
# setup.sh — one-click setup for the self-hosted Shorebird control plane.
#
#   ./setup.sh                          # single container, HTTP (dev + device testing)
#   ./setup.sh --domain cps.you.com     # single container + HTTPS (Caddy TLS)
#   ./setup.sh --scale --domain cps.you.com   # Postgres + S3/MinIO scale stack
#   ./setup.sh --down                   # stop everything
#   ./setup.sh --backup                 # snapshot the data volume (single-container)
#   ./setup.sh --restore <file.tgz>     # restore a snapshot (single-container)
#
# It generates all secrets, starts the stack, waits until healthy, and prints
# what to do next. Re-running is safe (keeps your .env).
set -euo pipefail
cd "$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

MODE=single DOMAIN="" EMAIL="" ACTION=up RESTORE_FILE=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --domain)  DOMAIN="${2:?--domain needs a hostname}"; shift 2 ;;
    --email)   EMAIL="${2:?--email needs an address}"; shift 2 ;;
    --scale)   MODE=scale; shift ;;
    --down)    ACTION=down; shift ;;
    --backup)  ACTION=backup; shift ;;
    --restore) ACTION=restore; RESTORE_FILE="${2:?--restore needs a file}"; shift 2 ;;
    -h|--help) sed -n '2,16p' "$0"; exit 0 ;;
    *) echo "unknown arg: $1" >&2; exit 2 ;;
  esac
done

say()  { printf '\033[36m==>\033[0m %s\n' "$*"; }
ok()   { printf '\033[32m ✓\033[0m %s\n' "$*"; }
die()  { printf '\033[31mERROR:\033[0m %s\n' "$*" >&2; exit 1; }
gen()  { openssl rand -hex 32; }

command -v docker >/dev/null 2>&1 || die "Docker is required — install Docker Desktop / Engine first."
docker compose version >/dev/null 2>&1 || die "The Docker Compose plugin is required (docker compose)."

# TLS single-container needs both compose files; scale uses the prod stack.
TLS=0; [[ -n "$DOMAIN" ]] && TLS=1
if [[ "$MODE" == scale ]]; then
  [[ -n "$DOMAIN" ]] || die "--scale needs --domain <host> (the scale stack terminates TLS at Caddy)."
  COMPOSE=(docker compose -f docker-compose.prod.yaml)
elif [[ "$TLS" == 1 ]]; then
  COMPOSE=(docker compose -f docker-compose.yaml -f docker-compose.tls.yaml)
else
  COMPOSE=(docker compose)  # single container, HTTP
fi

# --- resolve the single-container data volume (for backup/restore) ----------
data_volume() {
  local cid v
  cid="$(docker compose ps -q server 2>/dev/null | head -1)"
  if [[ -n "$cid" ]]; then
    v="$(docker inspect "$cid" -f '{{range .Mounts}}{{if eq .Destination "/data"}}{{.Name}}{{end}}{{end}}' 2>/dev/null)"
    [[ -n "$v" ]] && { echo "$v"; return; }
  fi
  docker volume ls -q | grep -E 'cps_data$' | head -1
}

case "$ACTION" in
  down)
    say "Stopping the stack…"; "${COMPOSE[@]}" down; ok "Stopped."; exit 0 ;;
  backup)
    V="$(data_volume)"; [[ -n "$V" ]] || die "No single-container data volume found (scale mode: use ops/backup.sh)."
    mkdir -p backups; STAMP="$(date -u +%Y%m%dT%H%M%SZ)"; NAME="cps-backup-$STAMP.tgz"
    say "Backing up volume $V (brief pause)…"
    "${COMPOSE[@]}" stop server >/dev/null 2>&1 || true
    docker run --rm -v "$V":/data -v "$PWD/backups":/backup busybox \
      tar czf "/backup/$NAME" -C /data .
    "${COMPOSE[@]}" start server >/dev/null 2>&1 || true
    ok "Wrote backups/$NAME  ($(du -h "backups/$NAME" | cut -f1)). Copy it off-host."
    exit 0 ;;
  restore)
    [[ -f "$RESTORE_FILE" ]] || die "no such file: $RESTORE_FILE"
    ABS="$(cd "$(dirname "$RESTORE_FILE")" && pwd)/$(basename "$RESTORE_FILE")"
    V="$(data_volume)"; [[ -n "$V" ]] || V="$(basename "$PWD" | tr 'A-Z' 'a-z')_cps_data"
    say "Restoring $ABS into $V (DESTRUCTIVE, brief pause)…"
    "${COMPOSE[@]}" stop server >/dev/null 2>&1 || true
    docker run --rm -v "$V":/data -v "$(dirname "$ABS")":/backup busybox \
      sh -c "rm -rf /data/* /data/..?* 2>/dev/null; tar xzf /backup/$(basename "$ABS") -C /data"
    "${COMPOSE[@]}" up -d >/dev/null 2>&1
    ok "Restored. Server restarting."
    exit 0 ;;
esac

# --- detect a device-reachable base URL (local mode) ------------------------
lan_ip() {
  if command -v ipconfig >/dev/null 2>&1; then
    ipconfig getifaddr en0 2>/dev/null || ipconfig getifaddr en1 2>/dev/null || true
  fi
  command -v hostname >/dev/null 2>&1 && hostname -I 2>/dev/null | awk '{print $1}' || true
}

# --- generate .env once -----------------------------------------------------
if [[ -f .env ]]; then
  say "Using existing .env (delete it to regenerate)."
elif [[ "$MODE" == scale ]]; then
  say "Generating .env with fresh secrets (scale: Postgres + S3/MinIO)…"
  : "${EMAIL:=admin@$DOMAIN}"; DBPW="$(gen)"; MINPW="$(gen)"
  cat > .env <<EOF
# Generated by setup.sh ($(date -u +%FT%TZ)) — SCALE (Postgres + S3). Never commit.
DOMAIN=$DOMAIN
ACME_EMAIL=$EMAIL
PRODUCTION=true
PORT=8080
PUBLIC_BASE_URL=https://$DOMAIN
SHOREBIRD_JWT_ISSUER=https://$DOMAIN
DATABASE_URL=postgres://cps:$DBPW@postgres:5432/code_push
S3_ENDPOINT=http://minio:9000
S3_ACCESS_KEY=cps
S3_SECRET_KEY=$MINPW
S3_BUCKET=code-push-artifacts
API_KEY=sb_api_$(gen)
JWT_SECRET=$(gen)
URL_SIGNING_SECRET=$(gen)
DOWNLOAD_URL_TTL=300
RATE_LIMIT_PER_MINUTE=600
RATE_LIMIT_BACKEND=postgres
LOGIN_EMAIL=$EMAIL
POSTGRES_USER=cps
POSTGRES_PASSWORD=$DBPW
POSTGRES_DB=code_push
MINIO_ROOT_USER=cps
MINIO_ROOT_PASSWORD=$MINPW
BACKUP_DIR=./backups
EOF
  ok ".env written."
elif [[ "$TLS" == 1 ]]; then
  say "Generating .env with fresh secrets (single container + HTTPS)…"
  : "${EMAIL:=admin@$DOMAIN}"
  cat > .env <<EOF
# Generated by setup.sh ($(date -u +%FT%TZ)) — single container + TLS. Never commit.
# Backend: embedded SQLite + filesystem artifacts (cps_data volume). No Postgres/MinIO.
DOMAIN=$DOMAIN
ACME_EMAIL=$EMAIL
PRODUCTION=true
PUBLIC_BASE_URL=https://$DOMAIN
API_KEY=sb_api_$(gen)
JWT_SECRET=$(gen)
URL_SIGNING_SECRET=$(gen)
LOGIN_EMAIL=$EMAIL
EOF
  ok ".env written."
else
  say "Generating .env with fresh secrets (single container, local)…"
  IP="$(lan_ip)"; BASE="http://${IP:-localhost}:8080"
  cat > .env <<EOF
# Generated by setup.sh ($(date -u +%FT%TZ)) — single container, local. Never commit.
# Backend: embedded SQLite + filesystem artifacts (cps_data volume). No Postgres/MinIO.
# PUBLIC_BASE_URL must be reachable from your test device (detected LAN IP).
PUBLIC_BASE_URL=$BASE
API_KEY=sb_api_$(gen)
JWT_SECRET=$(gen)
URL_SIGNING_SECRET=$(gen)
LOGIN_EMAIL=you@example.com
EOF
  ok ".env written."
fi

# --- start ------------------------------------------------------------------
say "Building and starting the stack (first run pulls images + builds the server)…"
"${COMPOSE[@]}" up -d --build

# --- wait for readiness -----------------------------------------------------
set -a; . ./.env; set +a
if [[ -n "$DOMAIN" ]]; then HEALTH="https://$DOMAIN/readyz"; CURLF=(-sk); BASE_URL="https://$DOMAIN"
else HEALTH="http://localhost:8080/readyz"; CURLF=(-s); BASE_URL="$PUBLIC_BASE_URL"; fi

say "Waiting for the server to become ready…"
READY=0
for _ in $(seq 1 60); do
  if curl "${CURLF[@]}" "$HEALTH" 2>/dev/null | grep -q '"db":true'; then READY=1; break; fi
  sleep 1
done
[[ "$READY" == 1 ]] || die "Server did not become ready. Check logs: ${COMPOSE[*]} logs server"
ok "Server is up and ready ($HEALTH)."

# --- print next steps -------------------------------------------------------
[[ "$MODE" == scale ]] && FOOTPRINT="scale: Postgres + S3/MinIO" || FOOTPRINT="single container: SQLite + files (one volume)"
cat <<EOF

────────────────────────────────────────────────────────────────────────────
 🎉  Your self-hosted Shorebird control plane is running.
     ($FOOTPRINT)

   Server URL   : $BASE_URL
   API key      : $API_KEY
   Console      : $BASE_URL/console     (dashboard)

 To ship an app through it — from your Flutter app directory:

   export SHOREBIRD_HOSTED_URL=$BASE_URL
   export SHOREBIRD_TOKEN=$API_KEY
   shorebird init                       # then add to shorebird.yaml:
                                        #   base_url: $BASE_URL
   shorebird release android
   shorebird patch android

 Common commands:
   ${COMPOSE[*]} logs -f server         # tail logs
   ./setup.sh --down                    # stop everything
   ./setup.sh --backup                  # snapshot the data volume
   BASE=$BASE_URL KEY=$API_KEY tool/smoke_test.sh   # self-test (no device)
────────────────────────────────────────────────────────────────────────────
EOF
