#!/usr/bin/env bash
# cspell:words dartaotruntime pkgs
#
# build_route_b_sdk_packages.sh -- package `sky_engine.zip` and
# `flutter_gpu.zip` FROM THIS ENGINE'S OWN TREE.
#
# WHY THIS EXISTS. Discovered 2026-08-25 while crossing the P6 device epoch:
# every cell in the chain 2c4443ce -> 93a3756 -> ac5d3b63 -> 9b5f040c hosts six
# artifacts and NEITHER of these is among them. `flutter_cache.dart`'s
# `FlutterSdk.getPackageDirs()` requires both, so a build from an EMPTY cache
# cannot complete on any of those hashes -- releases only ever worked because the
# cache retained a `pkg/sky_engine` fetched under a DIFFERENT engine hash, which
# the cache stamp made look settled. Twenty-three overlay hashes host
# sky_engine.zip and not one shares this engine.
#
# BORROWING ONE WAS REFUSED. That would ship a `dart:ui` source package from
# another engine build beside this engine's runtime -- the exact
# mixed-provenance shape this fork exists to remove, done deliberately this time.
#
# SOURCES, and why each is this engine's own:
#
#   sky_engine   out/ios_release/gen/dart-pkg/sky_engine -- GENERATED by this
#                engine build (288 files, LICENSE/AUTHORS/README/lib/sdk_ext).
#                The host_release_arm64 copy holds one file and is NOT usable.
#   flutter_gpu  flutter/lib/gpu -- SOURCES in this pinned tree, 23 files whose
#                names match what the reference zips carry. The engine's own
#                packaging copies these; nothing is compiled.
#
# DETERMINISM IS REQUIRED, not incidental: the cell address will cover these
# digests, so the same tree must produce the same bytes. zip embeds mtimes and
# directory order, so both are normalised -- fixed timestamp, sorted entries,
# no extra attributes. Verified by packaging twice and comparing.
set -euo pipefail

SRC=${SRC:-/Volumes/build/route-b/flutter/engine/src}
IOS_OUT=${IOS_OUT:-$SRC/out/ios_release}
OUTDIR=${OUTDIR:-${OUT:-$SRC/out/host_release_arm64}/zip_archives}
# A fixed timestamp so the digest is a function of CONTENT, not of when it ran.
# 2020-01-01 00:00, chosen once and never varied.
STAMP=${STAMP:-202001010000}

die() { echo "ERROR: $*" >&2; exit 1; }
note() { echo; echo "==> $*"; }

[ -d "$IOS_OUT/gen/dart-pkg/sky_engine/lib" ] \
  || die "no generated sky_engine at $IOS_OUT/gen/dart-pkg/sky_engine"
[ -d "$SRC/flutter/lib/gpu" ] || die "no flutter/lib/gpu in $SRC"
mkdir -p "$OUTDIR"

REV=$(git -C "$SRC/flutter" rev-parse HEAD 2>/dev/null || echo unknown)

# license_stub <dist-path> -> the root LICENSE.zip_old_location.md
#
# The engine's packaging emits this with the engine revision interpolated. Ours
# names THIS engine's revision, so a reader can tell which tree it came from
# rather than inheriting a pointer to somebody else's commit.
license_stub() {
  cat <<EOF
# _zip_old_location_license_md

This bundle is part of the the Flutter SDK.

The source code is hosted at [flutter/engine/$1](https://github.com/flutter/engine/tree/$REV/$1).
The license for this bundle is hosted at [flutter/engine/sky/packages/sky_engine/LICENSE](https://github.com/flutter/engine/tree/$REV/sky/packages/sky_engine/LICENSE)
and [sky_engine.zip](https://storage.googleapis.com/flutter_infra_release/flutter/$REV/sky_engine.zip).
EOF
}

# pack <name> <source-dir> <inner-dir> <dist-path-for-license>
pack() {
  local name=$1 src=$2 inner=$3 dist=$4
  local stage; stage=$(mktemp -d)
  mkdir -p "$stage/$inner"
  # -a would drag over extended attributes that differ per machine; a plain
  # recursive copy of regular files keeps the archive a function of content.
  (cd "$src" && find . -type f -print0 | while IFS= read -r -d '' f; do
     mkdir -p "$stage/$inner/$(dirname "$f")"
     cp "$src/$f" "$stage/$inner/$f"
   done)
  license_stub "$dist" > "$stage/LICENSE.zip_old_location.md"

  # NORMALISE, then archive in sorted order. Without both, two runs from one
  # tree produce different digests and the cell address becomes a function of
  # the clock.
  find "$stage" -exec touch -t "$STAMP" {} +
  local zip="$OUTDIR/$name.zip"
  rm -f "$zip"
  (cd "$stage" && find . -type f -o -type d | sed 's|^\./||' | grep -v '^\.$' \
     | LC_ALL=C sort | zip -q -X -o "$zip" -@)
  rm -rf "$stage"
  echo "    $name.zip  $(wc -c < "$zip" | tr -d ' ') bytes  $(unzip -l "$zip" | tail -1 | awk '{print $2}') entries"
  shasum -a 256 "$zip" | sed 's/^/      /'
}

note "packaging from this engine's own tree (revision $REV)"
pack sky_engine "$IOS_OUT/gen/dart-pkg/sky_engine" sky_engine \
  sky/packages/sky_engine
pack flutter_gpu "$SRC/flutter/lib/gpu" flutter_gpu lib/gpu/dist

note "determinism check: repackage and compare"
for n in sky_engine flutter_gpu; do
  before=$(shasum -a 256 "$OUTDIR/$n.zip" | cut -d' ' -f1)
  cp "$OUTDIR/$n.zip" "$OUTDIR/.$n.first"
done
pack sky_engine "$IOS_OUT/gen/dart-pkg/sky_engine" sky_engine \
  sky/packages/sky_engine >/dev/null
pack flutter_gpu "$SRC/flutter/lib/gpu" flutter_gpu lib/gpu/dist >/dev/null
fail=0
for n in sky_engine flutter_gpu; do
  if cmp -s "$OUTDIR/.$n.first" "$OUTDIR/$n.zip"; then
    echo "    $n.zip: REPRODUCIBLE"
  else
    echo "    $n.zip: NOT REPRODUCIBLE — the cell address would depend on the clock"
    fail=1
  fi
  rm -f "$OUTDIR/.$n.first"
done
[ "$fail" -eq 0 ] || die "packaging is not deterministic; refusing to publish"

for n in sky_engine flutter_gpu; do
  cat > "$OUTDIR/$n.zip.provenance" <<EOF
Route B $n.zip — packaged from THIS engine's own tree
built        : $(date -u +%FT%TZ)
engine tree  : $SRC/flutter
engine rev   : $REV
source       : $([ "$n" = sky_engine ] && echo "$IOS_OUT/gen/dart-pkg/sky_engine (generated by this build)" || echo "$SRC/flutter/lib/gpu (sources in this pinned tree)")
zip sha256   : $(shasum -a 256 "$OUTDIR/$n.zip" | cut -d' ' -f1)
determinism  : fixed mtime $STAMP, sorted entries, zip -X. Verified by
               packaging twice and comparing bytes.
why          : no hash in the cell chain 2c4443ce..9b5f040c hosts this artifact,
               so a build from an EMPTY cache could not complete. Borrowing one
               from another engine's hash was refused: it would place a dart:ui
               source package from a different build beside this runtime.
EOF
done

echo
echo "built $OUTDIR/{sky_engine,flutter_gpu}.zip"
