#!/usr/bin/env bash
# cspell:words killgate dynmod depot APFS gclient
#
# create_checkout.sh — build Route B its OWN Dart/engine checkout.
#
# WHY THIS EXISTS: ROUTE_B.md's pre-Step-1 item #2. Route B needs
# dart_dynamic_modules=true, the killgate SDK changes, AND the VM/compiler
# changes at the same time. The shipping iOS-engine tree cannot carry the
# killgate SDK edits: they modify sdk/lib/_internal/vm/lib/internal_patch.dart
# and sdk/lib/internal/internal.dart, which compile into platform_strong.dill
# regardless of the GN flag, and mixing them into an iOS engine build fails the
# AOT step with "Unexpected tag 4 (Field)" — a message that names nothing
# useful. Sharing a checkout here is the ambient-state trap.
#
# The clone is an APFS copy-on-write clone (`cp -Rc`), so it costs ~0 bytes and
# ~90 seconds rather than a multi-hour gclient sync over the network. The
# source tree's blocks are shared until one side writes.
#
# Idempotent: refuses to clobber an existing checkout.
set -euo pipefail

SRC_TREE=${SRC_TREE:-/Volumes/build/ios-engine/flutter}
DEST_ROOT=${DEST_ROOT:-/Volumes/build/route-b}
DEST_TREE="$DEST_ROOT/flutter"
HERE="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
REPO="$(cd "$HERE/../../.." && pwd)"
DART="$DEST_TREE/engine/src/flutter/third_party/dart"

die() { echo "error: $*" >&2; exit 1; }
say() { echo "==> $*"; }

[[ -d "$SRC_TREE" ]] || die "source tree missing: $SRC_TREE (is the build SSD mounted?)"
[[ -e "$DEST_TREE" ]] && die "destination already exists: $DEST_TREE (remove it deliberately, this script will not)"

say "APFS-cloning $SRC_TREE -> $DEST_TREE"
mkdir -p "$DEST_ROOT"
cp -Rc "$SRC_TREE" "$DEST_TREE"

# The cloned out/ dirs carry the SOURCE tree's absolute paths in their ninja
# files and the wrong GN config. They are regenerated by build_host.sh; keeping
# them would only invite a build that silently reuses the other rig's config.
say "dropping cloned out/ (stale paths + wrong GN config)"
rm -rf "$DEST_TREE/engine/src/out"

say "verifying the four Dart patches survived the clone"
"$REPO/selfhost/engine/dart_patches.sh" --dest "$DART" --verify

say "applying the killgate SDK/native patch (this is what forces a dedicated tree)"
KG="$REPO/selfhost/engine/killgate/0001-attach-bytecode-native.patch"
if git -C "$DART" apply --check -p1 "$KG" 2>/dev/null; then
  git -C "$DART" apply -p1 "$KG"
elif git -C "$DART" apply --check -p1 -R "$KG" 2>/dev/null; then
  say "  already applied"
else
  die "killgate patch does not apply cleanly to $DART"
fi

# Verify by CONTENT, never by exit code — a wrong -p level makes `git apply`
# exit 0 having changed nothing (this cost real time in the killgate bring-up).
say "verifying by content"
fail=0
while IFS=: read -r sentinel file; do
  n=$(grep -c "$sentinel" "$DART/$file" 2>/dev/null || echo 0)
  printf '    %-38s %-52s %s\n' "$sentinel" "$file" "$n"
  [[ "$n" -gt 0 ]] || fail=1
done <<'PROBES'
Internal_attachBytecodeToFunction:runtime/lib/object.cc
Internal_attachBytecodeToFunction:runtime/vm/bootstrap_natives.h
attachBytecodeToFunction:sdk/lib/internal/internal.dart
attachBytecodeToFunction:sdk/lib/_internal/vm/lib/internal_patch.dart
PROBES
[[ "$fail" -eq 0 ]] || die "killgate patch reported success but its changes are not in the tree"

say "re-verifying the four Dart patches after the killgate patch"
"$REPO/selfhost/engine/dart_patches.sh" --dest "$DART" --verify

# Step 1 itself. Kept as a patch rather than living only in the working tree,
# because that is exactly the ambient-state trap the Spike A instrumentation set
# (see HANDOFF.md): a working-tree edit is invisible, unversioned, and silently
# inherited by every out-dir built from the tree.
say "applying Route B step 1: the patchable static-call form"
RB="$HERE/0001-patchable-static-calls.patch"
if git -C "$DART" apply --check -p1 "$RB" 2>/dev/null; then
  git -C "$DART" apply -p1 "$RB"
elif git -C "$DART" apply --check -p1 -R "$RB" 2>/dev/null; then
  say "  already applied"
else
  die "step 1 patch does not apply cleanly to $DART"
fi
while IFS=: read -r sentinel file; do
  n=$(grep -c "$sentinel" "$DART/$file" 2>/dev/null || echo 0)
  printf '    %-30s %-56s %s\n' "$sentinel" "$file" "$n"
  [[ "$n" -gt 0 ]] || die "step 1 patch reported success but $sentinel is not in the tree"
done <<'ROUTEB_PROBES'
patchable_static_calls:runtime/vm/compiler/backend/flow_graph_compiler.cc
patchable_static_calls:runtime/vm/compiler/backend/flow_graph_compiler_arm64.cc
LookupClassAllowPrivate:runtime/lib/object.cc
ROUTEB_PROBES

cat <<EOF

Route B checkout ready: $DEST_TREE
  flutter revision : $(git -C "$DEST_TREE" rev-parse --short HEAD)
  dart tree        : $DART
  carries          : 0001/0004/0005/0006 + killgate + Route B step 1

Next: $HERE/build_host.sh
EOF
