#!/usr/bin/env bash
# cspell:words armeabi embedding armv canonicalizer
# stage_android_cell.sh -- assemble the 30-member macos-ios-android stage.
#
# FIFTEEN MEMBERS ARE THE DONOR'S EXACT PUBLISHED BYTES. The iOS engine, the
# host toolchain, the Dart SDK, the sky packages, the patch differs and the
# Route B compiler are not the subject of this cell: it ADDS Android. Copying
# them from the overlay rather than rebuilding is what makes "byte-identical"
# a checkable claim instead of a hope -- and stage_h2_cell.sh records why
# re-zipping is not an option (`zip` stamps mtimes, so a re-stage of identical
# inputs is a different archive than the one that was addressed).
#
# ONE macOS/iOS MEMBER DOES CHANGE, and it must: artifacts_manifest.yaml is the
# cell's own self-description and its `# target:` line said `ios`. Carrying that
# forward onto a cell that also serves Android would be a quiet falsehood in the
# record. It is REGENERATED by the product's own generator with
# `--target ios+android`, so the change is two comment lines and the override
# list is copied verbatim. Reported as 15 byte-identical + 1 regenerated, never
# as 16 byte-identical.
#
# FOURTEEN MEMBERS ARE NEW and every one was built by us, from engine revision
# $PRODUCER_REV, whose parent is exactly the donor's producer.
#
# The POMs are staged through lib/v2_canonicalize.py with the PRODUCER revision
# as the hash. That is not a trick: the built POM's own version line is exactly
# `<version>1.0.0-<producer></version>`, which is the one shape that schema
# permits, so the canonicalizer converts it to the `%H` template AND refuses if
# the producer revision appears anywhere else in the file. One authority, used
# in both directions.
set -uo pipefail
HERE="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
SELFHOST="$(cd "$HERE/../.." >/dev/null 2>&1 && pwd)"
OVERLAY=${OVERLAY:-$SELFHOST/cdn/overlay}
CELL_DONOR=${DONOR:-cd848320d605ff8af5060cabf9a8d1b35853f752}
PRODUCER_REV=${PRODUCER_REV:-f1a59b8a1609c51397601c36d586ad7763d57153}
MEMBERS=${MEMBERS:?set MEMBERS to the dir holding the 14 built Android members}
STAGE=${STAGE:?set STAGE to the output stage dir}
FLUTTER_REV=${FLUTTER_REV:-371005c93a7c927b34bbd727eb2c4951f0ef090d}
DART_REV=${DART_REV:-9e8c898a4d2a3b4d0f9c76b973a199859bb1b40c}
MINT_CELL_LIB_ONLY=1 . "$HERE/mint_route_b_cell.sh"
DONOR="$CELL_DONOR"
set +e
die() { echo "ERROR: $*" >&2; exit 1; }

FI='flutter_infra_release/flutter/%H'
SB='download.shorebird.dev/shorebird/%H'
MV='download.flutter.io/io/flutter'
rm -rf "$STAGE"

# --- 14 unchanged macOS/iOS members, the donor's exact published bytes -------
for m in "$FI/dart-sdk-darwin-arm64.zip" "$FI/darwin-arm64/artifacts.zip" \
         "$FI/darwin-arm64/font-subset.zip" "$FI/flutter_gpu.zip" \
         "$FI/flutter_patched_sdk.zip" "$FI/flutter_patched_sdk_product.zip" \
         "$FI/ios-release/artifacts.zip" "$FI/ios/artifacts.zip" \
         "$FI/ios-profile/artifacts.zip" "$FI/sky_engine.zip" \
         "$SB/patch-darwin-arm64.zip" "$SB/patch-darwin-x64.zip" \
         "$SB/patch-linux-x64.zip" \
         "$SB/route-b-compiler-darwin-arm64.zip"; do
  v2_stage_install "$STAGE" "$m" "$OVERLAY/${m/\%H/$DONOR}" || die "$m"
done

# --- engine_stamp.json: canonicalized to its %H template ---------------------
mkdir -p "$STAGE/$FI" "$STAGE/$SB"
v2_canonicalize "$OVERLAY/flutter_infra_release/flutter/$DONOR/engine_stamp.json" "$DONOR" \
  > "$STAGE/$FI/engine_stamp.json" || die "engine_stamp canonicalization"

# --- artifacts_manifest.yaml: REGENERATED, target ios+android ----------------
bash "$SELFHOST/engine/generate_manifest.sh" \
  --hash '%H' \
  --base-manifest "$OVERLAY/download.shorebird.dev/shorebird/$DONOR/artifacts_manifest.yaml" \
  --flutter-revision "$FLUTTER_REV" --dart-revision "$DART_REV" \
  --host darwin-arm64 --target ios+android \
  --out "$STAGE/$SB/artifacts_manifest.yaml" >/dev/null || die "manifest generation"
grep -q '^# target:                ios+android$' "$STAGE/$SB/artifacts_manifest.yaml" \
  || die "regenerated manifest does not declare target ios+android"

# --- 6 Android engine members ------------------------------------------------
for abi in arm arm64 x64; do
  for obj in darwin-x64 artifacts; do
    v2_stage_install "$STAGE" "$FI/android-$abi-release/$obj.zip" \
      "$MEMBERS/android-$abi-release--$obj.zip" || die "android-$abi-release/$obj.zip"
  done
done

# --- 8 Maven members ---------------------------------------------------------
for art in arm64_v8a_release armeabi_v7a_release x86_64_release flutter_embedding_release; do
  src_base="$MEMBERS/$art-1.0.0-$PRODUCER_REV"
  dst_dir="$MV/$art/1.0.0-%H"
  v2_stage_install "$STAGE" "$dst_dir/$art-1.0.0-%H.jar" "$src_base.jar" || die "$art jar"
  mkdir -p "$STAGE/$dst_dir"
  v2_canonicalize "$src_base.pom" "$PRODUCER_REV" > "$STAGE/$dst_dir/$art-1.0.0-%H.pom" \
    || die "$art pom canonicalization (the producer revision is not confined to <version>)"
  grep -qF '<version>1.0.0-%H</version>' "$STAGE/$dst_dir/$art-1.0.0-%H.pom" \
    || die "$art pom did not template to 1.0.0-%H"
done

# --- the stage must be exactly 30 members ------------------------------------
n=$(cd "$STAGE" && find . -type f | wc -l | tr -d ' ')
[[ "$n" == 30 ]] || die "staged $n files, expected 30"

# --- prove the delta ---------------------------------------------------------
same=0; changed=0; new=0
while IFS= read -r rel; do
  donor_file="$OVERLAY/${rel//%H/$DONOR}"
  if [[ ! -f "$donor_file" ]]; then echo "  NEW      $rel"; new=$((new+1)); continue; fi
  a=$(shasum -a 256 "$donor_file" | cut -d' ' -f1)
  b=$(shasum -a 256 "$STAGE/$rel" | cut -d' ' -f1)
  if [[ "$a" == "$b" ]]; then same=$((same+1)); else
    changed=$((changed+1)); echo "  CHANGED  $rel"
  fi
done < <(cd "$STAGE" && find . -type f | sed 's|^\./||' | sort)
# engine_stamp.json and artifacts_manifest.yaml are compared as TEMPLATES against
# the donor's RENDERED bytes, so both necessarily report as changed. The
# canonical-form comparison is the meaningful one for engine_stamp.
es_a=$(v2_canonicalize "$OVERLAY/flutter_infra_release/flutter/$DONOR/engine_stamp.json" "$DONOR" | shasum -a 256 | cut -d' ' -f1)
es_b=$(shasum -a 256 "$STAGE/$FI/engine_stamp.json" | cut -d' ' -f1)
[[ "$es_a" == "$es_b" ]] && echo "  engine_stamp.json canonical form: IDENTICAL to the donor's" \
                         || echo "  engine_stamp.json canonical form: DIFFERS"
echo "staged $n members: $same byte-identical to the donor, $changed changed, $new new"
