#!/usr/bin/env python3
"""Collect every candidate module-validation SOURCE, with its properties.

The B0 verdict is a function of source roles, so this is where the facts about
each candidate come from. Nothing here decides anything; it records.

DISCOVERY IS NOT DONE HERE ANY MORE. It comes from discover_policies.py over
the universe from consumer_universe.py. The previous version decided
"production consumer" from three filename globs, which covered 12 of Route B's
38 scripts and pointed `scripts/*.sh` at 5 repo-root files while the 58
producer scripts live under selfhost/scripts. It therefore missed the ACTUAL
production consumer: patch_command.dart passes
--extra-front-end-options=--dynamic-interface=<release supplement>, and
ios_releaser.dart generates that interface during the release.

RELEASE-BOUND MEANS PRODUCED FROM A SPECIFIC RELEASE. Not "committed", and not
"referenced". A static committed YAML is the same file for every release, so a
different release inherits it unchanged and re-running a release cannot
reproduce it -- which is what "deterministic, release-bound" excludes. The
release supplement's interface is release-bound because the release generates
it from its own prepass kernel; a probe fixture is not, however many sections
it carries and however many scripts name it.

usage: collect_sources.py <repo-root> <discovery.json> <generated-spec>
                          <generated-attempt-log> <extra-attempts.json> <out>
"""
import hashlib
import json
import pathlib
import re
import sys

REPO = pathlib.Path(sys.argv[1])
DISCOVERY = json.loads(pathlib.Path(sys.argv[2]).read_text())
GEN_SPEC = pathlib.Path(sys.argv[3])
GEN_ATTEMPT = pathlib.Path(sys.argv[4])
EXTRA = pathlib.Path(sys.argv[5])
OUT = sys.argv[6]

SECTIONS = ['callable', 'extendable', 'can-be-overridden',
            'can-be-used-as-type']


def read(p):
    try:
        return p.read_text(errors='replace')
    except Exception:                                        # noqa: BLE001
        return None


def sha(p):
    try:
        return hashlib.sha256(p.read_bytes()).hexdigest()
    except Exception:                                        # noqa: BLE001
        return None


def sections_in(text):
    return {s: bool(re.search(rf'^{re.escape(s)}:', text, re.M))
            for s in SECTIONS}


try:
    extra = json.loads(EXTRA.read_text())
except Exception:                                            # noqa: BLE001
    extra = {}

sources = {}

# ---- 1. the PRODUCTION path: the release supplement's interface --------
# Generated by ios_releaser.dart during the release, captured into the release
# supplement, and passed to BOTH the release build and the patch build. This is
# the source the previous universe missed entirely.
arg_sites = DISCOVERY.get('argument_sites', [])
supplement_consumers = sorted({
    a['consumer'] for a in arg_sites
    if 'retentionInterface' in a['argument'] or 'interface' in a['argument']})
gen_text = read(GEN_SPEC)
attempt = read(GEN_ATTEMPT)
sources['release_supplement_interface'] = {
    'what': 'dynamic_interface.yaml, generated per release by '
            'ios_releaser.dart via the Route B generator and captured into the '
            'release supplement; patch_command.dart compiles the patch against '
            'the same file',
    'release_bound': True,
    'why_release_bound': "generated from the release's own prepass kernel "
                         'under a named --policy, so the same release '
                         'reproduces it and a different release gets its own',
    'release_consumed': bool(supplement_consumers),
    'consumers': supplement_consumers,
    'consumer_tiers': sorted({a['tier'] for a in arg_sites
                              if a['consumer'] in supplement_consumers}),
    'passed_as': '--dynamic-interface (retention/annotation), never --validate',
    'spec_path': str(GEN_SPEC),
    'spec_sha256': sha(GEN_SPEC),
    'sections': sections_in(gen_text) if gen_text is not None
    else {x: None for x in SECTIONS},
    'validated_positive': bool(
        attempt and re.search(r'^produced=yes', attempt, re.M)),
    'refusal_kinds': {
        'extendable': len(re.findall(
            r'Cannot extend, implement or mix-in class', attempt or '')),
        'can-be-overridden': len(re.findall(
            r'Cannot override member', attempt or '')),
        'can-be-used-as-type': len(re.findall(
            r'Cannot use class .* as a type', attempt or '')),
        'callable': len(re.findall(r'Cannot invoke member', attempt or '')),
    },
}

# ---- 2. every committed policy discovery found ------------------------
for c in DISCOVERY.get('committed_policies', []):
    rel = c['path']
    sources[f'committed_policy:{rel}'] = {
        'what': f'{rel}, a committed file carrying the permission keys',
        # Static and identical for every release: not release-bound.
        'release_bound': False,
        'why_unusable': 'a static committed file is the same for every '
                        'release, so a release cannot reproduce it and a '
                        'different release inherits it unchanged. Referenced '
                        f'by {len(c["referenced_by"])} universe member(s) '
                        f'in tiers {c["consumer_tiers"] or "none"}, which '
                        'makes it consumed but not release-bound.',
        'release_consumed': c['release_consumed'],
        'consumers': c['referenced_by'],
        'consumer_tiers': c['consumer_tiers'],
        'spec_path': rel,
        'spec_sha256': c['sha256'],
        'sections': c['sections'],
        'validated_positive': bool(extra.get(rel, {}).get('produced_module')),
    }

# ---- 3. producers that EMIT permission keys ---------------------------
for e in DISCOVERY.get('emitted_policies', []):
    sources[f'emitted_policy:{e["consumer"]}'] = {
        'what': f'{e["consumer"]} emits permission keys itself, so the policy '
                'has no committed file',
        'release_bound': False,
        'why_unusable': 'the keys are written by the producer, not derived '
                        f'from a release. Emits {e["permission_keys_emitted"]}'
                        f', all four = {e["all_four"]}.',
        'release_consumed': True,
        'consumers': [e['consumer']],
        'consumer_tiers': [e['tier']],
        'sections': {x: (x in e['permission_keys_emitted'] or x == 'callable'
                         and False) for x in SECTIONS},
        'validated_positive': False,
    }

# ---- 4. the semantic map's admitted set -------------------------------
sub = REPO / 'selfhost/engine/semantic_map/g5_patchability/evidence/subset.json'
admitted, verdict = None, None
try:
    _s = json.loads(sub.read_text())
    admitted, verdict = _s['predicted_patchable'], _s['verdict']
except Exception:                                            # noqa: BLE001
    pass
sources['semantic_map_admitted_set'] = {
    'what': "SEMANTIC-MAP-1's set of declarations established safely patchable",
    'release_bound': True,
    'release_consumed': False,
    'sections': {x: False for x in SECTIONS},
    'validated_positive': False,
    'admitted': admitted,
    'map_verdict': verdict,
    'why_unusable': (
        f'admits {admitted} declarations and no converter to a validation '
        'specification exists. Even a nonzero count would not make it a '
        'source without a converter whose output is demonstrated to validate.'),
}

# ---- 5. the module itself: permanently ineligible ---------------------
sources['the_module_itself'] = {
    'what': 'reading the required permissions off the patch being validated',
    'release_bound': False,
    'release_consumed': False,
    'permanently_ineligible': True,
    'sections': {x: True for x in SECTIONS},
    'validated_positive': True,
    'why_unusable': (
        'it would permit whatever the patch does, so validation would refuse '
        'nothing. Recorded with every property SATISFIED on purpose: if the '
        'role rule can be talked into promoting it, that is a defect the '
        'record should expose rather than hide.'),
}

json.dump({
    'schema': 'route-b-di-1/b0-sources/2',
    'sources': sources,
    'discovery_summary': {
        'universe_total': DISCOVERY.get('universe_total'),
        'universe_counts': DISCOVERY.get('universe_counts'),
        'text_files_scanned': DISCOVERY.get('text_files_scanned'),
        'committed_policies': len(DISCOVERY.get('committed_policies', [])),
        'argument_sites': len(arg_sites),
        'emitted_policies': len(DISCOVERY.get('emitted_policies', [])),
        'negative_existential': DISCOVERY.get('negative_existential'),
    },
}, open(OUT, 'w'), indent=2)

for name, s in sources.items():
    sup = sorted(k for k, v in (s['sections'] or {}).items() if v)
    print(f'  {name}\n    sections={sup or "none"} '
          f'bound={s.get("release_bound")} '
          f'consumed={s.get("release_consumed")} '
          f'validated={s.get("validated_positive")}')
