#!/usr/bin/env python3
"""Emit a host declaring N patchable members, plus its complete contract.

SL1-G6B measured +16,704 bytes for ONE declared-patchable member and said the
number must not be multiplied naively. This generates the family that tests
that: the same program shape at several N, so the actual curve is measured
rather than assumed linear.

Every member is structurally identical, so N is the only variable. No member
carries a retaining pragma -- the confound this gate exists to control.
"""
import sys
from pathlib import Path

LIB = "package:dynamic_modules/scale_host.dart"


def host(n):
    members = "\n".join(
        f"  @pragma('vm:never-inline')\n"
        f"  String work{i}() => 'AOT-{i}';"
        for i in range(n)
    )
    calls = "\n".join(f"    sink += t.work{i}().length;" for i in range(n))
    return f"""// GENERATED by lib/gen_scale_host.py -- do not edit.
// {n} patchable member(s). No retaining pragma appears on any of them.
class Target {{
{members}
}}

@pragma('vm:never-inline')
int callAll(Target t) {{
  var sink = 0;
{calls}
  return sink;
}}

void main() {{
  print('SCALE_N={n} sink=' + callAll(Target()).toString());
}}
"""


def di(n):
    ov = "\n".join(
        f"  - library: '{LIB}'\n    class: 'Target'\n    member: 'work{i}'"
        for i in range(n)
    )
    ca = "\n".join(
        f"  - library: '{LIB}'\n    class: 'Target'\n    member: 'work{i}'"
        for i in range(n)
    )
    return (
        f"extendable:\n  - library: '{LIB}'\n    class: 'Target'\n"
        f"can-be-used-as-type:\n  - library: '{LIB}'\n    class: 'Target'\n"
        f"can-be-overridden:\n{ov}\n"
        f"callable:\n  - library: '{LIB}'\n    class: 'Target'\n    member: ''\n{ca}\n"
    )


if __name__ == '__main__':
    n = int(sys.argv[1])
    out = Path(sys.argv[2])
    out.mkdir(parents=True, exist_ok=True)
    (out / 'scale_host.dart').write_text(host(n))
    (out / 'di_scale.yaml').write_text(di(n))
    print(f'  N={n} -> {out}')
