#!/usr/bin/env python3
"""Derive the flavored `project.pbxproj` from the pinned Flutter's generated one.

WHY THIS EXISTS RATHER THAN A HAND-EDITED BLOB
----------------------------------------------
The overlay ships as a COMMITTED `project.pbxproj` gated by a sha, not as
scripted surgery at prepare time, because the `xcodeproj` ruby gem is not
importable on this host — it exists only inside cocoapods' vendored gems:

    ruby -e "require 'xcodeproj'"   ->  LoadError

A committed blob with no derivation is unmaintainable the first time Flutter
bumps, so the derivation lives here as an auditable transform. It is NOT run by
`prepare_flavored_fixture.sh`; that script copies the committed output. Run this
only when the baseline changes, and commit the new output plus the new sha.

    ./derive_overlay.py <generated-project.pbxproj> <output-project.pbxproj>

Exit 2 means the input is not the baseline this overlay was derived from — the
overlay is NOT APPLICABLE to that tree, which is a different finding from
"unrun" and must be recorded as one (H2's NOT RUNNABLE clause).

WHAT IT ADDS
------------
Six build configurations (three modes x two flavors) to each of the three
configuration lists — the PBXProject, the Runner target, and the RunnerTests
target. All three, because the flavored schemes carry a TestAction that names
RunnerTests, and a target missing the named configuration is an xcodebuild
error rather than a fallback.

The Runner TARGET's flavored configurations get the flavor xcconfig as their
`baseConfigurationReference`, and their hardcoded `PRODUCT_BUNDLE_IDENTIFIER`
is REMOVED: a build setting written in the pbxproj overrides the xcconfig that
configuration includes, so leaving it would silently pin both flavors to one
bundle id and they could not co-install. That is the whole reason the setting is
deleted here rather than rewritten.
"""

import hashlib
import re
import sys

# sha256 of ios/Runner.xcodeproj/project.pbxproj as generated by
#   flutter create --platforms=ios,android --project-name flavored_probe \
#                  --org dev.selfhost .
# at flutter_revision c15ef6379403a0a55531a058bdb2c8e55bc05c98 (3.44.8 /
# Dart 3.12.2), measured 2026-08-13 in a scratch directory and confirmed
# byte-identical to the fixture's own generated copy.
BASELINE_SHA = "18152845ff6073752b926099b37b738d0415b49575fe11be1bdca3f7c1997387"

FLAVORS = ["Foo", "Bar"]
MODES = ["Debug", "Release", "Profile"]

# Deterministic 24-hex-char object ids, in Xcode's shape but far outside the
# generator's ranges so a collision is impossible and a flavored object is
# recognizable on sight.
FILEREF_ID = {"Foo": "FA0000000000000000000031", "Bar": "FA0000000000000000000032"}
BASE_ID = {"project": 1, "Runner": 11, "RunnerTests": 21}


def obj_id(kind: str, flavor: str, mode: str) -> str:
    n = BASE_ID[kind] + FLAVORS.index(flavor) * 3 + MODES.index(mode)
    return f"FA{n:022d}"


def read_section(text: str, name: str) -> tuple[int, int]:
    begin = text.index(f"/* Begin {name} section */")
    end = text.index(f"/* End {name} section */")
    return begin, end


def main() -> int:
    src, dst = sys.argv[1], sys.argv[2]
    raw = open(src, "rb").read()
    got = hashlib.sha256(raw).hexdigest()
    if got != BASELINE_SHA:
        sys.stderr.write(
            f"REFUSED: baseline mismatch.\n  expected {BASELINE_SHA}\n  got      {got}\n"
            "The overlay was derived from a different generator. Re-derive it against\n"
            "the current pinned Flutter and record the new sha; do NOT overlay anyway.\n"
        )
        return 2
    text = raw.decode()

    # --- which XCBuildConfiguration belongs to which list -----------------------
    lb, le = read_section(text, "XCConfigurationList")
    lists = {}
    for m in re.finditer(
        r'\t\t([0-9A-F]{24}) /\* Build configuration list for (PBXProject|PBXNativeTarget) "(\w+)" \*/ = \{'
        r"(.*?)\n\t\t\};",
        text[lb:le],
        re.S,
    ):
        kind = "project" if m.group(2) == "PBXProject" else m.group(3)
        members = dict(
            (mm.group(2), mm.group(1))
            for mm in re.finditer(r"\t\t\t\t([0-9A-F]{24}) /\* (\w+) \*/,", m.group(4))
        )
        lists[kind] = {"uuid": m.group(1), "members": members}
    missing = set(BASE_ID) - set(lists)
    if missing:
        sys.stderr.write(f"REFUSED: configuration lists not found: {sorted(missing)}\n")
        return 3

    # --- clone each configuration block, once per flavor ------------------------
    cb, ce = read_section(text, "XCBuildConfiguration")
    blocks = {
        m.group(1): m.group(0)
        for m in re.finditer(
            r"\t\t([0-9A-F]{24}) /\* \w+ \*/ = \{\n\t\t\tisa = XCBuildConfiguration;.*?\n\t\t\};",
            text[cb:ce],
            re.S,
        )
    }
    new_blocks, added = [], {k: [] for k in BASE_ID}
    for kind, info in lists.items():
        for mode, uuid in info["members"].items():
            for flavor in FLAVORS:
                nid, name = obj_id(kind, flavor, mode), f"{mode}-{flavor}"
                b = blocks[uuid]
                b = b.replace(f"\t\t{uuid} /* {mode} */ = {{", f"\t\t{nid} /* {name} */ = {{", 1)
                b = b.replace(f"\n\t\t\tname = {mode};", f"\n\t\t\tname = {name};", 1)
                if kind == "Runner":
                    ref = f"\t\t\tbaseConfigurationReference = {FILEREF_ID[flavor]} /* {flavor}.xcconfig */;"
                    b = re.sub(r"\t\t\tbaseConfigurationReference = [^\n]*", ref, b, count=1)
                    # See the module docstring: the xcconfig cannot win against a
                    # setting written here, so the setting goes.
                    b = re.sub(r"\n\t\t\t\tPRODUCT_BUNDLE_IDENTIFIER = [^\n]*", "", b, count=1)
                new_blocks.append(b)
                added[kind].append((nid, name))

    out = text[:ce] + "".join(b + "\n" for b in new_blocks) + text[ce:]

    # --- register the two xcconfig file references ------------------------------
    refs = "".join(
        f"\t\t{FILEREF_ID[f]} /* {f}.xcconfig */ = {{isa = PBXFileReference; "
        f"lastKnownFileType = text.xcconfig; name = {f}.xcconfig; "
        f'path = Flutter/{f}.xcconfig; sourceTree = "<group>"; }};\n'
        for f in FLAVORS
    )
    anchor = "\t\t9740EEB31CF90195004384FC /* Generated.xcconfig */ = {isa = PBXFileReference;"
    i = out.index(anchor)
    out = out[:i] + refs + out[i:]
    group_anchor = "\t\t\t\t9740EEB31CF90195004384FC /* Generated.xcconfig */,\n"
    j = out.index(group_anchor) + len(group_anchor)
    out = out[:j] + "".join(f"\t\t\t\t{FILEREF_ID[f]} /* {f}.xcconfig */,\n" for f in FLAVORS) + out[j:]

    # --- append the new ids to each configuration list ---------------------------
    for kind, info in lists.items():
        head = f"\t\t{info['uuid']} /* Build configuration list for "
        k = out.index(head)
        k = out.index("\t\t\t);", k)
        out = out[:k] + "".join(f"\t\t\t\t{i} /* {n} */,\n" for i, n in added[kind]) + out[k:]

    open(dst, "w").write(out)
    print(f"baseline  {BASELINE_SHA}")
    print(f"overlay   {hashlib.sha256(out.encode()).hexdigest()}")
    print(f"added     {sum(len(v) for v in added.values())} configurations: "
          + ", ".join(f"{m}-{f}" for f in FLAVORS for m in MODES))
    return 0


if __name__ == "__main__":
    sys.exit(main())
