#!/usr/bin/env python3
"""Generate SM1-G5's closeout report and provenance manifest.

Every number is DERIVED from banked evidence. Nothing is transcribed: a report
that restates counts by hand drifts from the run it describes, which this lane
has already had happen twice (a stale 28-arm figure, and an assertion count in
prose).

usage: gen_final_report.py <gate-dir> <head-sha> <out.md> <out-manifest.json>
"""
import hashlib
import json
import pathlib
import re
import sys

G, HEAD, OUT_MD, OUT_MAN = sys.argv[1:5]
E = pathlib.Path(G) / 'evidence'
# This generator's own products, excluded from the input digests below.
GENERATED = {pathlib.Path(OUT_MAN).name, pathlib.Path(OUT_MD).name}


def sha(p):
    return hashlib.sha256(pathlib.Path(p).read_bytes()).hexdigest()


def load(name):
    return json.load(open(E / name))


def text(name):
    return (E / name).read_text()


man = load('../instrumentation/MANIFEST.json')
state = load('inlining_state.json')
preds = load('predictions.json')
subset = load('subset.json')
corpora = {n: load(f'corpus_{n}.json') for n in ('localsend', 'wonderous')}

# --- falsification and control counts, parsed from the transcripts ---------
def arms(name):
    return re.findall(r'arms=(\d+) passed=(\d+) failed=(\d+)', text(name))


banks = {
    'reader falsification (34 ELF/framing/mapper arms)':
        ('reader_falsification.txt', arms('reader_falsification.txt')),
    'predictor refusal bank (one arm per reason)':
        ('predictor_falsification.txt', arms('predictor_falsification.txt')),
    'subset scorer sensitivity':
        ('subset_check.txt', arms('subset_check.txt')),
    'dispatch predicate':
        ('dispatch_experiment.txt', arms('dispatch_experiment.txt')),
    'manifest semantic identity':
        ('reader_state.txt', arms('reader_state.txt')),
}

# --- admitted / excluded declaration classes, derived from the predictor ---
src = pathlib.Path(G, 'lib', 'predict_patchable.dart').read_text()
vb = src[src.index('const refusalReasons'):src.index(
    '];', src.index('const refusalReasons'))]
vocab = sorted(set(re.findall(r"'([A-Z_]+)'", vb)))

kinds = {}
for r in preds['rows']:
    kinds.setdefault(r['kind'], {'n': 0, 'admitted': 0})
    kinds[r['kind']]['n'] += 1
    if r.get('predicted_patchable') is True:
        kinds[r['kind']]['admitted'] += 1

# THE SCOPE EXCLUSION IS PROVEN, NOT INFERRED FROM PRESENCE. A reason can
# appear in the histogram and still be absent from one row -- and that row is
# precisely the one that would be admissible. So it is checked per row on the
# adversarial corpus, and read from each app corpus's banked per-row proof.
SCOPE = ('CALL_SITE_SHAPE_UNPROVEN', 'FRONTEND_MATERIALIZATION_UNPROVEN')
m = re.search(r"const \{([^}]*)\}\.contains\(kind\)", src)
if m is None:
    raise SystemExit('cannot locate the replaceable-kind set in the predictor')
REPLACEABLE = set(re.findall(r"'(\w+)'", m.group(1)))

adv_repl = [r for r in preds['rows'] if r['kind'] in REPLACEABLE]
adv_missing = [r['key'] for r in adv_repl
               if not all(c in r['refusal_reasons'] for c in SCOPE)]

scope_proof = {
    'adversarial': {
        'replaceable_declarations': len(adv_repl),
        'missing_a_scope_reason': len(adv_missing),
        'covers_every_replaceable': not adv_missing,
    },
}
for n, c in corpora.items():
    pr = c.get('scope_exclusion_proof')
    if pr is None:
        raise SystemExit(f'{n}: corpus summary carries no scope_exclusion_proof; '
                         f'REDUCE_SCOPE cannot be justified from it')
    scope_proof[n] = {
        'replaceable_declarations': pr['replaceable_declarations'],
        'missing_a_scope_reason': pr['replaceable_missing_a_scope_reason'],
        'covers_every_replaceable': pr['covers_every_replaceable'],
    }
scope_holds_everywhere = all(v['covers_every_replaceable']
                             for v in scope_proof.values())
unconditional = list(SCOPE)

total_admitted = (preds['predicted_patchable']
                  + sum(c['predicted_patchable'] for c in corpora.values()))

# REDUCE_SCOPE requires BOTH: nothing admitted anywhere, AND a proven predicate
# that excludes the whole replaceable class on every corpus. Zero admitted
# alone would also be produced by an accident of the corpus, which is not a
# scope reduction -- it is a coincidence.
if total_admitted != 0:
    disposition = 'REVIEW_REQUIRED'
elif not scope_holds_everywhere:
    disposition = 'REVIEW_REQUIRED'
else:
    disposition = 'REDUCE_SCOPE'

md = []
w = md.append
w('# SEMANTIC-MAP-1 / G5 — patchability capability and over-claim safety')
w('')
w('Generated by `lib/gen_final_report.py`. Every figure below is derived from')
w('banked evidence; none is transcribed.')
w('')
w('## Identity')
w('')
w('```text')
w(f"experimental HEAD          {HEAD}")
w(f"frozen effective tree      {man['base']['frozen_effective_tree']}")
w(f"frozen dart revision       {man['base']['dart_revision']}")
w(f"instrumented gen_snapshot  {man['built']['instrumented_gen_snapshot_sha256_schema6']}")
w(f"canonical release kernel   {man['route2_witness']['subject']['input_kernel']}")
w(f"  sha256                   {man['route2_witness']['subject']['input_kernel_sha256']}")
w(f"canonical release AOT      {man['route2_witness']['subject']['aot']}")
w(f"  sha256                   {man['route2_witness']['subject']['aot_sha256']}")
w(f"route-2 note section       {man['route2_witness']['determinism']['note_section_sha256']}")
w(f"  schema / fields / records {man['route2_witness']['note_schema_version']}"
  f" / {man['route2_witness']['fields_per_record']}"
  f" / {man['route2_witness']['records']}")
w('```')
w('')
w('The capability marker is read from the artifact itself, not assumed:')
w('')
w('```text')
for n, c in corpora.items():
    w(f"{n:11} release_patch_capability = {c['release_patch_capability']}")
w('```')
w('')
w('## Route-2 reader state, adversarial corpus')
w('')
w('```text')
for k, v in state['accounting'].items():
    w(f"{k:16} {v:>6}")
w(f"{'unprojected':16} {state['unprojected_count']:>6}")
w(f"{'note_validated':16} {str(state['note_validated']):>6}")
w(f"{'complete':16} {str(state['note_complete_projection']):>6}")
w('```')
w('')
w('## Predictor refusals, adversarial corpus')
w('')
w('```text')
for k, v in sorted(preds['refusal_histogram'].items(),
                   key=lambda x: (-x[1], x[0])):
    w(f"{v:6}  {k}")
w('```')
w('')
w('## Declaration classes')
w('')
w('| kind | declarations | admitted |')
w('|---|---:|---:|')
for k in sorted(kinds):
    w(f"| {k} | {kinds[k]['n']} | {kinds[k]['admitted']} |")
w('')
w('**Excluded, and by what predicate.** Both of these are asserted to be')
w('present on EVERY replaceable declaration, per row, on every corpus — not')
w('merely present in the aggregate histogram:')
w('')
for c in unconditional:
    w(f'* `{c}`')
w('')
w(f'Replaceable kinds, read from the predictor: '
  f'{", ".join("`" + k + "`" for k in sorted(REPLACEABLE))}.')
w('')
w('| corpus | replaceable | missing a scope reason | covers all |')
w('|---|---:|---:|---|')
for n, v in scope_proof.items():
    w(f"| {n} | {v['replaceable_declarations']} | "
      f"{v['missing_a_scope_reason']} | {v['covers_every_replaceable']} |")
w('')
w('## Corpora')
w('')
w('| corpus | declarations | admitted | subset | demonstration | coverage |')
w('|---|---:|---:|---|---|---|')
w(f"| adversarial | {preds['count']} | {preds['predicted_patchable']} | "
  f"{subset['verdict']} | {subset['behavioral_demonstration']} | "
  f"{subset['coverage_diagnostic_only']} |")
for n, c in corpora.items():
    w(f"| {n} | {c['declarations']} | {c['predicted_patchable']} | "
      f"{c['subset_verdict']} | {c['behavioral_demonstration']} | "
      f"{c['coverage_diagnostic_only']} |")
w('')
w('## Falsification and controls')
w('')
w('```text')
for label, (fn, a) in banks.items():
    if not a:
        continue
    shipped = a[0]
    ctrls = a[1:]
    w(f"{label}")
    w(f"    shipped   arms={shipped[0]} passed={shipped[1]} failed={shipped[2]}")
    for i, c in enumerate(ctrls, 1):
        w(f"    control {i} arms={c[0]} passed={c[1]} failed={c[2]}")
w('```')
w('')
w('## Refusal vocabulary')
w('')
w(f'{len(vocab)} reasons, every one exercised by an arm with its own')
w('sensitivity control. A reason in the vocabulary with no arm fails the run.')
w('')
w('```text')
for c in vocab:
    w(f"{preds['refusal_histogram'].get(c, 0):6}  {c}")
w('```')
w('')
w('## Disposition')
w('')
w(f'### {disposition}')
w('')
w('Two things are required, and both are proven above: nothing is admitted on')
w('any corpus, AND both scope reasons are present on every replaceable')
w('declaration of every corpus. Zero-admitted alone would not justify this —')
w('that could be an accident of the corpus rather than a scope reduction.')
w('')
w('Zero replaceable declarations are admitted on any corpus. The subset')
w('property `predicted ⊆ demonstrated` holds everywhere it was checked, and')
w('holds **vacuously** on all three corpora — which is recorded as a distinct')
w('verdict (`SUBSET_HOLDS_VACUOUSLY`) precisely so it cannot be read as')
w('evidence that anything is patchable.')
w('')
w('**Coverage was not used as a safety gate.** It is reported as a diagnostic')
w('and never gates publication; the verdict above would be identical at any')
w('coverage figure, and a single admitted-but-undemonstrated declaration would')
w('make it `FAIL_OPEN` regardless of how high coverage were.')
w('')
w('## What is NOT established')
w('')
w('* That any declaration is safely patchable. Nothing is admitted.')
w('* That `NOT_INLINED` implies a patch takes effect. `Base.work` is')
w('  `NOT_INLINED`, attaches, invokes as patched — and an ordinary polymorphic')
w('  call site still reads the old value.')
w('* That a pool-indirect call shape is redirectable. `UntaggedFunction` and')
w('  `UntaggedCode` entry-point offsets alias, so the redirectable and')
w('  non-redirectable forms are byte-identical in the shipped text.')
w('* That front-end materialization is witnessed by any VM-level evidence.')
w('* Behavioural patchability on the app corpora: not measured, and not')
w('  required for an empty prediction set.')

pathlib.Path(OUT_MD).write_text('\n'.join(md) + '\n')

manifest = {
    'schema': 'semantic-map-1/g5-final/1',
    'gate': 'SM1-G5', 'issue': 54,
    'experimental_head': HEAD,
    'disposition': disposition,
    'coverage_used_as_safety_gate': False,
    'identity': {
        'frozen_effective_tree': man['base']['frozen_effective_tree'],
        'dart_revision': man['base']['dart_revision'],
        'gen_snapshot_sha256':
            man['built']['instrumented_gen_snapshot_sha256_schema6'],
        'release_kernel_sha256':
            man['route2_witness']['subject']['input_kernel_sha256'],
        'release_aot_sha256': man['route2_witness']['subject']['aot_sha256'],
        'route2_note_section_sha256':
            man['route2_witness']['determinism']['note_section_sha256'],
    },
    # IDEMPOTENT. The generator's OWN outputs are excluded, or a rerun hashes
    # the previous manifest into the new one and the manifest never converges.
    'inputs': {p.name: sha(p) for p in sorted(E.iterdir())
               if p.is_file() and p.name not in GENERATED},
    'scripts': {p.name: sha(p) for p in
                sorted(pathlib.Path(G).glob('run_*.sh'))},
    'tools': {p.name: sha(p) for p in sorted(pathlib.Path(G, 'lib').iterdir())
              if p.is_file() and p.suffix in ('.py', '.dart', '.sh')},
    'corpora': {n: {'declarations': c['declarations'],
                    'predicted_patchable': c['predicted_patchable'],
                    'subset_verdict': c['subset_verdict'],
                    'release_aot_sha256': c['release_aot_sha256']}
                for n, c in corpora.items()},
    'adversarial': {'declarations': preds['count'],
                    'predicted_patchable': preds['predicted_patchable'],
                    'subset_verdict': subset['verdict']},
    'scope_exclusion_proof': scope_proof,
    'scope_holds_on_every_corpus': scope_holds_everywhere,
    'refusal_vocabulary': vocab,
}
json.dump(manifest, open(OUT_MAN, 'w'), indent=2)
print(f'  {OUT_MD}  ({len(md)} lines)')
print(f'  {OUT_MAN}  ({len(manifest["inputs"])} evidence inputs, '
      f'{len(manifest["tools"])} tools)')
print(f'  disposition: {disposition}')
