#!/usr/bin/env bash
# prepare_airgap_fixture.sh — materialize the canonical air-gap acceptance
# fixture and its pub seed, so the sealed run never again depends on a path
# somebody remembered.
#
# WHY THIS EXISTS
#
# The 2026-08-06 sealed acceptance passed against an iOS app that lived in a
# session scratchpad. The scratchpad was cleaned, the path was never recorded,
# and the run therefore could not be reproduced — the fixture was ephemeral,
# which means the acceptance was too. Same for AIRGAP_PUB_CACHE, which was
# passed as an ambient machine path.
#
# What is COMMITTED (selfhost/fixtures/airgap_app):
#   pubspec.yaml, pubspec.lock, lib/main.dart, assets/probe.json,
#   shorebird.yaml.template
#
# What is GENERATED here (gitignored, reproducible):
#   ios/ android/ .dart_tool/   — `flutter create` output; bulky and derived
#   the pub seed                 — a real resolved cache, from the lockfile
#
#   prepare_airgap_fixture.sh [--app-id <id>] [--hosted-url <url>]
#                             [--seed-out <dir>] [--skip-seed]
#
# Afterwards:
#   selfhost/scripts/airgap_run.sh -- selfhost/scripts/airgap_acceptance.sh \
#     --ios --app selfhost/fixtures/airgap_app
# (the harness defaults --app to that path, so it can usually be omitted)
set -euo pipefail

HERE="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
FIXTURE="$HERE/../fixtures/airgap_app"
SEED_OUT="$HERE/../fixtures/airgap/pub-cache"
APP_ID=""; HOSTED_URL="http://localhost:18080"; SKIP_SEED=0
SHOREBIRD="${SHOREBIRD:-$HOME/.shorebird/bin/shorebird}"

die() { echo "ERROR: $*" >&2; exit 1; }
note() { echo "==> $*"; }

while [[ $# -gt 0 ]]; do
  case "$1" in
    --app-id) APP_ID="${2:?}"; shift 2 ;;
    --hosted-url) HOSTED_URL="${2:?}"; shift 2 ;;
    --seed-out) SEED_OUT="${2:?}"; shift 2 ;;
    --skip-seed) SKIP_SEED=1; shift ;;
    -h|--help) sed -n '2,30p' "${BASH_SOURCE[0]}"; exit 0 ;;
    *) die "unknown argument: $1" ;;
  esac
done

[[ -d "$FIXTURE" ]] || die "no fixture at $FIXTURE"
command -v flutter >/dev/null || die "flutter is not on PATH"

FIXTURE="$(cd "$FIXTURE" && pwd)"

# --- platform scaffolding ------------------------------------------------------
# `flutter create` over an existing directory fills in the missing platform
# dirs and leaves committed files (pubspec.yaml, lib/, assets/) alone. It is
# how the bulky generated tree stays out of git without the fixture being
# unbuildable.
if [[ ! -d "$FIXTURE/ios" || ! -d "$FIXTURE/android" ]]; then
  note "materializing ios/ and android/ with flutter create"
  ( cd "$FIXTURE" && flutter create --platforms=ios,android \
      --project-name airgap_probe --org dev.selfhost . >/dev/null )
else
  note "ios/ and android/ already present"
fi

# --- shorebird.yaml ------------------------------------------------------------
# app_id is SERVER-GENERATED (POST /api/v1/apps ignores a requested id), so it
# cannot be committed as a constant — it differs per control-plane instance.
# Committed as shorebird.yaml.template; the real file is written here.
if [[ -n "$APP_ID" ]]; then
  cat > "$FIXTURE/shorebird.yaml" <<EOF
# GENERATED by selfhost/scripts/prepare_airgap_fixture.sh — do not hand-edit.
# app_id is server-generated and instance-specific, which is exactly why it is
# not a committed constant.
app_id: $APP_ID
base_url: $HOSTED_URL
EOF
  note "wrote shorebird.yaml (app_id $APP_ID, base_url $HOSTED_URL)"
elif [[ -f "$FIXTURE/shorebird.yaml" ]] && ! grep -q 'REPLACE-ME' "$FIXTURE/shorebird.yaml"; then
  note "shorebird.yaml already configured: $(awk '/^app_id:/{print $2}' "$FIXTURE/shorebird.yaml")"
else
  die "no app_id yet. Create the app on the control plane, then re-run with
       --app-id <id>. E.g.:
         curl -sS -X POST $HOSTED_URL/api/v1/apps \\
           -H \"Authorization: Bearer \$TOKEN\" \\
           -H 'Content-Type: application/json' \\
           -d '{\"display_name\":\"airgap-fixture\"}'"
fi

# --- pub seed ------------------------------------------------------------------
# The ONE cache the sealed run is allowed to bring in. Resolved from the
# COMMITTED lockfile into a dedicated directory, so the seed is a documented
# output rather than whatever happens to be in ~/.pub-cache.
if [[ $SKIP_SEED -eq 0 ]]; then
  note "seeding pub cache from the committed lockfile -> $SEED_OUT"
  mkdir -p "$SEED_OUT"
  SEED_OUT="$(cd "$SEED_OUT" && pwd)"
  ( cd "$FIXTURE" && PUB_CACHE="$SEED_OUT" flutter pub get >/dev/null ) \
    || die "pub get into the seed failed"
  # An index, so a later reader can tell whether the seed still matches the
  # lockfile without re-resolving.
  ( cd "$SEED_OUT" && find . -maxdepth 3 -type d -name "*-*" | sort ) \
    > "$SEED_OUT/../pub-cache.index"
  pkgs="$(wc -l < "$SEED_OUT/../pub-cache.index" | tr -d ' ')"
  lock_sha="$(shasum -a 256 "$FIXTURE/pubspec.lock" 2>/dev/null | awk '{print $1}')"
  cat > "$SEED_OUT/../SEED.txt" <<EOF
# GENERATED by selfhost/scripts/prepare_airgap_fixture.sh
seed_path:        $SEED_OUT
resolved_from:    $FIXTURE/pubspec.lock
pubspec_lock_sha: ${lock_sha:-unknown}
package_dirs:     $pkgs
index:            $(cd "$SEED_OUT/.." && pwd)/pub-cache.index

# Use it:  AIRGAP_PUB_CACHE=$SEED_OUT
# If pubspec.lock changes, re-run this script — the seed is derived, never
# hand-maintained, and never an ambient ~/.pub-cache.
EOF
  note "seed ready: $pkgs package dirs; contract in $(cd "$SEED_OUT/.." && pwd)/SEED.txt"
fi

note "fixture ready: $FIXTURE"
echo
echo "  AIRGAP_PUB_CACHE=$SEED_OUT"
echo "  --app $FIXTURE"
